### ISSUE TITLE
Mask webhook by utilizing env_var_name parameter type

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/spinnaker-orb#7]
Mask webhook which may be considered sensitive information with env_var_name parameter type: https://github.com/CircleCI-Public/spinnaker-orb/blob/master/src/commands/trigger-pipeline-with-webhook.yml#L8

> Utilize the [“env_var_name” parameter type](https://circleci.com/docs/2.0/reusing-config/#environment-variable-name) to secure API keys or other sensitive data.

from: https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L37

**Comment by piyush-insider** [comment]
Hi @KyleTryon I will pick this up.
